import type { ReactNode } from "react";
import Head from "next/head";

import Navbar from "./navbar";
import Footer from "./footer";

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Fun with Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col min-h-screen p-4 bg-purple-50 text-slate-700">
        <Navbar />
        <main className="flex flex-col flex-grow">{children}</main>
        <Footer />
      </div>
    </>
  );
}
